### ISSUE TITLE
Constant ContextsToViewTransformer::SEPARATOR does not exist

### ISSUE THREAD

**Issue by voriux** [oroinc/OroCalendarBundle#4] opened 2018-05-10 07:37 UTC
Hi,

https://github.com/oroinc/OroCalendarBundle/blob/2.6.5/Form/Type/CalendarEventAttendeesSelectType.php#L110

Currently oro/platform does not expose class constant ContextsToViewTransformer::SEPARATOR, so bundle versions starting from 2.6.2 fail with error:

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError:
"Undefined class constant 'SEPARATOR'" at
/vendor/oro/calendar-bundle/Form/Type/CalendarEventAttendeesSelectType.php line 129 
```

Thank you

**Comment by anyt** [comment] 2018-05-10 07:51
Duplicate of https://github.com/oroinc/platform/issues/827, 

You can find the workaround here https://github.com/oroinc/platform/issues/827#issuecomment-378616810

**Closed as completed by anyt** 2018-05-10 07:51 UTC
Labels: duplicate
